feat: [027-DOCKER-SET] docker 파일 생성
ValueWith/ValueWith_BE pull request #55
Opened 2023-11-12 00:52 UTC by wooooozin

### 변경사항

**AS-IS**
- Docker 배포 시 관련 설정
**TO-BE**
- master 기준으로 배포

2023-11-12 04:40 UTC, eod940 requested changes
확인했습니다. 고생많으셨어요!
다만 이전에 진행한 TripGroup 테스트 부분 수정이 필요하고, docker-compose를 따로 만들어 redis 추가해야 할 것 같습니다.
이 전까지는 배포하는건 안될 것 같아요!

2023-11-13 06:42 UTC, eod940 approved these changes

2023-11-13 07:54 UTC, dodunge commented
확인이 너무 늦어서 죄송합니다..
확인했습니다!
테스트부분 일단 주석처리후 배포해도 괜찮습니다!

2023-11-13 08:59 UTC, wooooozin commented
> 확인이 너무 늦어서 죄송합니다.. 확인했습니다! 테스트부분 일단 주석처리후 배포해도 괜찮습니다!

테스트 코드는 반영하지 않고 빌드해서 괜찮아요!

2023-11-13 10:06 UTC, eod940 commented
넵 확인했습니다.

2023-11-13 10:06 UTC, merged